# Generated by Django 3.0.6 on 2020-05-25 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(blank=True)),
                ('created', models.DateField(default='2020-05-25')),
                ('due_date', models.DateField(default='2020-05-25')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Category')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
